import "dotenv/config";
import AdmZip from "adm-zip";
import fs from "fs";
import path from "path";

// Regenerates src/services/deckTheme.ts from the repo-root corporate template
// (blueprint deck-studio.md §6.3). Run: npm run extract:theme
// Drift check (CI/qa): npm run extract:theme -- --check  → exit 1 on diff.

const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const TEMPLATE = path.join(REPO_ROOT, "AURIGO_PPT_TEMPLATE_2026.pptx");
const OUT = path.resolve(__dirname, "..", "src", "services", "deckTheme.ts");

const ROLE_META: [string, string, string][] = [
  ["dk1", "ink", "dk1  — darkest teal (section/closing backgrounds)"],
  ["lt1", "white", "lt1"],
  ["dk2", "tealDark", "dk2  — Aurigo Dark Teal (title bg, headings)"],
  ["lt2", "mist", "lt2  — light panels / column cards"],
  ["accent1", "tealLight", "accent1 — kickers, links, marks on dark"],
  ["accent2", "red", "accent2 — accent bar ONLY (never body text)"],
  ["accent3", "tealMid", "accent3"],
  ["accent4", "charcoal", "accent4 — body text on light"],
  ["accent5", "green", "accent5 (unused in MVP layouts)"],
  ["accent6", "orange", "accent6 (unused in MVP layouts)"],
  ["hlink", "hyperlink", ""],
];

function main() {
  const zip = new AdmZip(TEMPLATE);
  const theme = zip.getEntry("ppt/theme/theme1.xml")?.getData().toString("utf8");
  const pres = zip.getEntry("ppt/presentation.xml")?.getData().toString("utf8");
  if (!theme || !pres) throw new Error("Template is missing theme1.xml or presentation.xml");

  const colors = new Map<string, string>();
  for (const m of theme.matchAll(/<a:(\w+)>\s*<a:(?:srgbClr val|sysClr[^>]*lastClr)="([0-9A-Fa-f]{6})"/g)) {
    if (!colors.has(m[1])) colors.set(m[1], m[2].toUpperCase());
  }
  const majorFont = theme.match(/<a:majorFont>\s*<a:latin typeface="([^"]+)"/)?.[1] ?? "Calibri";
  const minorFont = theme.match(/<a:minorFont>\s*<a:latin typeface="([^"]+)"/)?.[1] ?? "Calibri";
  const sldSz = pres.match(/<p:sldSz cx="(\d+)" cy="(\d+)"/);
  const widthIn = sldSz ? Number((Number(sldSz[1]) / 914400).toFixed(3)) : 13.333;
  const heightIn = sldSz ? Number((Number(sldSz[2]) / 914400).toFixed(3)) : 7.5;

  const colorLines = ROLE_META.map(([role, name, comment]) => {
    const hex = colors.get(role);
    if (!hex) throw new Error(`Theme role ${role} not found in theme1.xml`);
    return `    ${name}: "${hex}",${comment ? ` // ${comment}` : ""}`;
  }).join("\n");

  const content = `// app/backend/src/services/deckTheme.ts — GENERATED by scripts/extract-deck-theme.ts. DO NOT EDIT.
export const DECK_THEME = {
  source: "AURIGO_PPT_TEMPLATE_2026.pptx",
  extracted: "${new Date().toISOString().slice(0, 10)}",
  colors: {
${colorLines}
  },
  fonts: { pptx: "${minorFont}", pptxBold: "${majorFont}", web: "Roboto" },
  // Template theme font is ${minorFont} — the .pptx uses it (safe on every
  // Windows/Office install, and matches the corporate template). The web
  // canvas uses Roboto per Aurigo Brand Standards + brand.css. Intentional.
  slide: { widthIn: ${widthIn}, heightIn: ${heightIn}, pptxLayout: "LAYOUT_WIDE" }, // ${sldSz ? `${sldSz[1]}×${sldSz[2]} EMU` : "assumed 16:9"}
  wordmark: { text: "AURIGO", charSpacingPt: 4, sizePt: 12 }, // bottom-right; logo artwork V2
} as const;
`;

  const check = process.argv.includes("--check");
  const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  // Compare everything except the volatile `extracted:` date line.
  const normalize = (s: string) => s.replace(/extracted: "[0-9-]+"/, 'extracted: "X"');
  if (check) {
    if (normalize(existing) !== normalize(content)) {
      console.error("deckTheme.ts is out of date with the template — run npm run extract:theme");
      process.exit(1);
    }
    console.log("deckTheme.ts matches the template.");
    return;
  }
  fs.writeFileSync(OUT, content, "utf8");
  console.log(`wrote ${OUT}`);
}

main();
