// app/backend/src/services/deckTheme.ts — GENERATED by scripts/extract-deck-theme.ts. DO NOT EDIT.
export const DECK_THEME = {
  source: "AURIGO_PPT_TEMPLATE_2026.pptx",
  extracted: "2026-08-11",
  colors: {
    ink: "053445", // dk1  — darkest teal (section/closing backgrounds)
    white: "FFFFFF", // lt1
    tealDark: "015F74", // dk2  — Aurigo Dark Teal (title bg, headings)
    mist: "EAEDF0", // lt2  — light panels / column cards
    tealLight: "46B2BE", // accent1 — kickers, links, marks on dark
    red: "EE3135", // accent2 — accent bar ONLY (never body text)
    tealMid: "38949F", // accent3
    charcoal: "383838", // accent4 — body text on light
    green: "6F9A35", // accent5 (unused in MVP layouts)
    orange: "E18527", // accent6 (unused in MVP layouts)
    hyperlink: "46B2BE",
  },
  fonts: { pptx: "Calibri", pptxBold: "Calibri bold", web: "Roboto" },
  // Template theme font is Calibri — the .pptx uses it (safe on every
  // Windows/Office install, and matches the corporate template). The web
  // canvas uses Roboto per Aurigo Brand Standards + brand.css. Intentional.
  slide: { widthIn: 13.333, heightIn: 7.5, pptxLayout: "LAYOUT_WIDE" }, // 12192000×6858000 EMU
  wordmark: { text: "AURIGO", charSpacingPt: 4, sizePt: 12 }, // bottom-right; logo artwork V2
} as const;
